stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: flemoi/greenshop
  DOCKER_TAG: ${CI_COMMIT_SHORT_SHA}

# Build de l'image Docker
docker-build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker pull $DOCKER_IMAGE:latest || true
    - docker build --cache-from $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:$DOCKER_TAG -t $DOCKER_IMAGE:latest .
  only:
    - main

# Tests de l'application (basiques)
app-test:
  stage: test
  image: $DOCKER_IMAGE:$DOCKER_TAG
  script:
    - echo "Vérification de base de l'image GreenShop"
    - if [ "$(docker inspect --format='{{.Config.ExposedPorts}}' $DOCKER_IMAGE:$DOCKER_TAG)" != "map[]" ]; then echo "L'image expose bien des ports"; else exit 1; fi
  only:
    - main

# Build de l'image Docker
docker-deploy:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker run -d $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - main