aws_region           = "us-east-1"  # Paris
project_name         = "greenshop"
vpc_cidr             = "10.0.0.0/16"
availability_zones   = ["us-east-1a", "us-east-1b"]
private_subnet_cidrs = ["10.0.1.0/24", "10.0.2.0/24"]
public_subnet_cidrs  = ["10.0.101.0/24", "10.0.102.0/24"]
bastion_ingress_cidr = ["45.141.123.46/32"]  # Remplacer par votre IP
key_name = "acces"  # Créer cette clé dans AWS EC2
bastion_instance_type = "t2.micro"
app_instance_type    = "t2.small"
asg_min_size         = 3
asg_max_size         = 5
asg_desired_capacity = 2
db_allocated_storage = 20
db_engine            = "mysql"
db_engine_version    = "8.0"
db_instance_class    = "db.t3.small"
db_name              = "greenshop"
db_username          = "admin"
db_password          = "YOUR_PASSWORD"  # À changer
