# inventory/hosts.yml
all:
  vars:
    # Optionnel : si vous préférez, vous pouvez aussi exposer un alias
    bastion_host: "{{ groups['bastion'][0] }}"

  hosts:
    192.168.50.82:
      ansible_user: localadm
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      db_user: root
      db_pass: root
      db_name: greenshop

  children:
    bastion:
      hosts:
        54.145.145.56:
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/migration.pem

    web:
      children:
        server-web1:
          hosts:
            10.0.2.103:
              ansible_user: ec2-user
              ansible_ssh_private_key_file: ~/.ssh/migration.pem
              ansible_ssh_common_args: >-
                -o StrictHostKeyChecking=no
                -o UserKnownHostsFile=/dev/null
                -o ProxyCommand="ssh -i /root/.ssh/migration.pem
                                  ec2-user@{{ groups['bastion'][0] }} -W %h:%p"
        server-web2:
          hosts:
            10.0.0.3:
              ansible_user: ec2-user
              ansible_ssh_private_key_file: ~/.ssh/migration.pem
              ansible_ssh_common_args: >-
                -o StrictHostKeyChecking=no
                -o UserKnownHostsFile=/dev/null
                -o ProxyCommand="ssh -i /root/.ssh/migration.pem
                                  ec2-user@{{ groups['bastion'][0] }} -W %h:%p"

