# inventory/hosts.yml
all:
  vars:
    # Optionnel : si vous préférez, vous pouvez aussi exposer un alias
    bastion_host: "{{ groups['bastion'][0] }}"



  children:

    target:
      hosts:
        target01:
          ansible_host: 192.168.50.82
          ansible_user: localadm
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          db_user: root
          db_pass: root
          db_name: greenshop
    bastion:
      hosts:
        bastion01:
          ansible_host: 52.90.119.105
          ansible_user: ec2-user
          ansible_ssh_private_key_file: /root/.ssh/migration.pem


web:
  vars:
    # Variable common_args pour tout le groupe web
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/migration.pem
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -o 'ProxyCommand=ssh -i /root/.ssh/migration.pem ec2-user@{{ hostvars[bastion_host].ansible_host }} -W %h:%p'
  children:
    server-web1:
      hosts:
        web01:
          ansible_host: 10.0.1.150

    server-web2:
      hosts:
        web02:
          ansible_host: 10.0.1.166
