# inventory/hosts.yml
all:
  vars:
    bastion_host: bastion01
  children:
    bastion:
      hosts:
        bastion01:
          ansible_host: 13.217.54.187
          ansible_user: ec2-user
          ansible_ssh_private_key_file: /root/.ssh/migration.pem

    web:
      hosts:
        web01:
          ansible_host: 10.0.1.133
        web02:
          ansible_host: 10.0.2.209
        web03:
          ansible_host: 10.0.2.142

      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: /root/.ssh/migration.pem
        ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
          -o ProxyCommand="ssh -i /root/.ssh/migration.pem \
              ec2-user@{{ hostvars[bastion_host].ansible_host }} -W %h:%p"
