# playbooks/copy_migration_key.yml
- name: Copier migration.pem vers le bastion
  hosts: bastion
  become: yes
  vars:
    migration_key_src: /root/.ssh/migration.pem

  tasks:
    - name: S'assurer que ~/.ssh existe
      ansible.builtin.file:
        path: /home/ec2-user/.ssh
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0700'

    - name: Copier migration.pem sur le bastion
      ansible.builtin.copy:
        src: "{{ migration_key_src }}"
        dest: /home/ec2-user/.ssh/migration.pem
        owner: ec2-user
        group: ec2-user
        mode: '0400'
