# playbooks/regenerate_ssh_key.yml
---
- name: Générer une paire de clés SSH Ed25519 sur la machine de contrôle
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Créer la clé privée/id_pub si nécessaire
      ansible.builtin.openssh_keypair:
        path: "{{ lookup('env','HOME') }}/.ssh/id_ed25519"
        type: ed25519
        size: 256
        force: no   # ne pas écraser si elle existe déjà

- name: Déployer la clé publique sur le serveur cible
  hosts: target
  become: yes
  tasks:
    - name: S'assurer que le répertoire .ssh de localadm existe
      ansible.builtin.file:
        path: /home/localadm/.ssh
        state: directory
        owner: localadm
        group: localadm
        mode: '0700'

    - name: Installer la clé publique dans authorized_keys
      ansible.builtin.authorized_key:
        user: localadm
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
