pipeline {
  agent any

  environment {
    IMAGE = 'flemoi/greenshop'
    TAG = 'latest'
    DOCKER_CREDS = 'dockerhub-credentials-id'
    DOCKERFILE_PATH = 'ansible_old/roles/docker/webapp/Dockerfile'
    BUILD_CONTEXT = '.'
  }

  stages {
    stage('Cloner la branche ansible') {
      steps {
        git branch: 'ansible', url: 'https://github.com/jolyjonathan/Hackaton_BAD.git'
      }
    }

    stage('Build Docker image') {
      steps {
        script {
          sh "docker build -t ${IMAGE_TAG} -f ${DOCKERFILE_PATH} ${BUILD_CONTEXT}"
        }
      }
    }

    stage('Push to DockerHub') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: "${DOCKER_CREDS}",
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
          sh "docker push ${IMAGE}:${TAG}"
        }
      }
    }
  }
}
