pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        echo '📥 Clonage du dépôt...'
        checkout scm
      }
    }

    stage('Build') {
      steps {
        echo '🔨 Étape de build simulée'
        sh 'echo "Hello from Jenkins!"'
      }
    }

    stage('Done') {
      steps {
        echo '✅ Pipeline terminé avec succès.'
      }
    }
  }
}
