pipeline {
  agent any

  environment {
    IMAGE = 'flemoi/greenshop'
    TAG = 'latest'
    DOCKER_CREDS = 'dockerhub-credentials-id'
    DOCKERFILE_PATH = 'ansible_old/roles/docker/webapp/Dockerfile'
    BUILD_CONTEXT = '.'
  }

  stages {
    stage('Cloner la branche ansible') {
      steps {
        git branch: 'ansible', url: 'https://github.com/jolyjonathan/Hackaton_BAD.git'
      }
    }

    stage('Build Docker image') {
      steps {
        script {
          // Générer un tag versionné
          def commit = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
          def dateTag = sh(script: 'date +%Y%m%d-%H%M', returnStdout: true).trim()
          def imageTag = "${IMAGE}:${dateTag}-${commit}"
          env.IMAGE_TAG = imageTag

          // Build de l’image avec le tag versionné
          sh "docker build -t ${imageTag} -t ${IMAGE}:${TAG} -f ${DOCKERFILE_PATH} ${BUILD_CONTEXT}"
        }
      }
    }

    stage('Push to DockerHub') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: "${DOCKER_CREDS}",
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
          sh "docker push ${IMAGE_TAG}"
          sh "docker push ${IMAGE}:${TAG}"
        }
      }
    }
  }
}
