name: Deploy GreenShop via Bastion

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-all:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH configuration
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh-keyscan ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts
          
          cat > ~/.ssh/config << EOF
          Host bastion
            HostName ${{ secrets.BASTION_HOST }}
            User ${{ secrets.BASTION_USER }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          
          Host *
            User ${{ secrets.TARGET_USER }}
            IdentityFile ~/.ssh/id_rsa
            ProxyJump bastion
            StrictHostKeyChecking no
          EOF
          
          chmod 600 ~/.ssh/config

      - name: Deploy to all target instances
        run: |
          # Créer un script de déploiement
          cat > deploy.sh << 'EOL'
          #!/bin/bash
          if ! command -v docker &> /dev/null; then
            echo "Docker n'est pas installé, installation en cours..."
            sudo amazon-linux-extras install docker -y || sudo apt-get update && sudo apt-get install -y docker.io
            sudo service docker start
            sudo usermod -a -G docker $USER
            sudo systemctl enable docker
            
            # Utiliser sudo pour cette exécution
            sudo docker pull flemoi/greenshop:latest
            sudo docker stop greenshop_container || true
            sudo docker rm greenshop_container || true
            sudo docker run -d -p 80:80 --name greenshop_container flemoi/greenshop:latest
          else
            # Docker est déjà installé
            docker pull flemoi/greenshop:latest
            docker stop greenshop_container || true
            docker rm greenshop_container || true
            docker run -d -p 80:80 --name greenshop_container flemoi/greenshop:latest
          fi
          echo "GreenShop déployé avec succès sur $(hostname)"
          docker ps | grep greenshop_container
          EOL
          
          chmod +x deploy.sh
          
          # Déployer sur chaque instance
          # Remplacer ces IP par vos vraies IP cibles ou utilisez une variable d'environnement
          for host in "10.0.1.10" "10.0.2.20" "10.0.3.30"; do
            echo "Déploiement sur $host..."
            scp -o ProxyJump=${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} deploy.sh ${{ secrets.TARGET_USER }}@$host:~/
            ssh -J ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} ${{ secrets.TARGET_USER }}@$host "./deploy.sh"
          done